version: "3.9"

services:
  smtp-aliaser:
    build:
      context: .
    container_name: smtp-aliaser
    restart: unless-stopped
    network_mode: host
    command: ["/config/example.json"]
    secrets:
      - server_key
      - server_crt
    volumes:
      - ./config:/config
    environment:
      VERIFY: true
      TZ: ${TZ:-UTC}

secrets:
  server_key:
    file: ./certs/server.key
  server_crt:
    file: ./certs/server.crt